vscode:
  extensions:
    - TI.devspacesplus
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: start api
    init: echo 'init script' # runs during prebuild
    before: gp sync-await multispace && source ~/.bashrc
    command: |
      pip install -r requirements.txt
      python api.py
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    visibility: public
    onOpen: open-browser
